language: elixir

matrix:
  include:
    - otp_release: 21.2
      elixir: 1.7.4

    - otp_release: 21.2
      elixir: 1.8.1

sudo: false

before_script:
  - mix deps.get --only test

script:
  - mix format --check-formatted
  - mix test
